theme = "awesome-identity"
baseURL = "https://my-hugo-project.billyfung.now.sh/"
title = "Super Cool Awesome"


## Profile Configurations
[params.profile]
  portrait = "/images/profile.jpg"
  firstname = "Billy"
  lastname = "Fung"
  title = "Tinkerer"
  bio = """This is my landing page for now while I work on redesigning my blog.
  
  I spend my time thinking about to improve efficiency of electricity grids and properly manage distributed resources in order to reduce need for fossil fuels. 
  """ 


[params.contacts]
  email = "billy@billyfung.com"
  github = "billyfung"
  resume = "billy-resume.pdf"

## Footer Configurations
[params.footer]
  copyright = "© 2019 Billy Fung. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = false
